-- Choosing the sakila database
USE sakila;


---- NOTES Section ----
-- This section of the code will just be notes about the chapter
-----------------------

-- This chapter is about sets, I have a pretty strong background in set
-- theory so might just be notes about syntax
-- union is UNION, this is the true union in set notation
-- alternatively you have UNION ALL, which will keep in duplicates
-- intersection is INTERSECT
-- set minus is EXCEPT


-- EXERCISES IN "TEST YOUR KNOWLEDGE" AT THE END OF THE CHAPTER --
-------------------------------------------
-- Exercise 6-1 --
-- If set A = {L, M, N, O, P} and set B = {P, Q, R, S, T} what sets are
-- generated by the following operations
-- A union B
-- A union all B
-- A intersect B
-- A except B

-- ANSWER --
-- A union B = {L, M, N, O, P, Q, R, S, T}
-- A union all B = {L, M, N, O, P, P, Q, R, S, T}
-- A intersect B = {P}
-- A except B = {L, M, N, O}

-------------------------------------------
-- Exercise 6-2 --
-- Write a compound query that finds the first and last names of all actors and
-- customers whose last name starts with L

-- ANSWER --
SELECT 'customer' type, first_name, last_name
  FROM customer
  WHERE last_name LIKE 'L%'
  UNION
SELECT 'actor' type, first_name, last_name
  FROM actor
  WHERE last_name LIKE 'L%';


-------------------------------------------
-- Exercise 6-3 --
-- Sort the results from Exercise 6-2 by the last_name column

-- ANSWER --
SELECT 'customer' type, first_name, last_name
  FROM customer
  WHERE last_name LIKE 'L%'
  UNION
SELECT 'actor' type, first_name, last_name
  FROM actor
  WHERE last_name LIKE 'L%'
  ORDER BY last_name;
